#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

plt.imshow(x_train[0], cmap='Greys')

x_train_flat = x_train.reshape(60000, 784)
x_test_flat = x_test.reshape(10000, 784)
x_train_flat = x_train_flat/255
x_test_flat = x_test_flat/255

y_train = np.array(pd.get_dummies(y_train))

y_test = np.array(pd.get_dummies(y_test))



model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000, activation='relu', 
                          input_shape=(x_train_flat.shape[1],)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
    
    ])

model.compile(loss='categorical_crossentropy', 
              optimazer=tf.keras.optimizers.Adam(learning_rate = 0.01),
              metrics=['categorical_accuracy'])

model.fit(x_train_flat, y_train, validation_data=(x_test_flat, y_test), 
          epochs=10, batch_size=100)

ennuste_test = model.predict(x_test_flat)

plt.imshow(x_test[321], cmap='Greys')

"""
Created on Sun Sep 27 18:24:58 2020

@author: outi
"""

**********
The Error

Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
Type "copyright", "credits" or "license" for more information.

IPython 7.18.1 -- An enhanced Interactive Python.

runfile('/Users/outi/Desktop/harkat/ht12.py', wdir='/Users/outi/Desktop/harkat')
2020-10-10 16:17:57.807026: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-10 16:17:57.807459: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 16. Tune using inter_op_parallelism_threads for best performance.
Train on 60000 samples, validate on 10000 samples
Epoch 1/10

Restarting kernel... 
 
[SpyderKernelApp] WARNING | No such comm: f3b6f4820afa11eb91d9faffc248b9c8

And after a while: "python quit unexpectedly"
